packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@scarf/scarf': true
  better-sqlite3: true
  esbuild: true
  msgpackr-extract: true
  msw: true
  unrs-resolver: true
