/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedProjectsProjectIdSdkKeysRouteImport } from './routes/_authenticated/projects/$projectId/sdk-keys'
import { Route as AuthenticatedProjectsProjectIdFlagsRouteImport } from './routes/_authenticated/projects/$projectId/flags'
import { Route as AuthenticatedProjectsProjectIdEnvironmentsRouteImport } from './routes/_authenticated/projects/$projectId/environments'
import { Route as AuthenticatedProjectsProjectIdFlagsFlagIdRouteImport } from './routes/_authenticated/projects/$projectId/flags/$flagId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdSdkKeysRoute =
  AuthenticatedProjectsProjectIdSdkKeysRouteImport.update({
    id: '/projects/$projectId/sdk-keys',
    path: '/projects/$projectId/sdk-keys',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdFlagsRoute =
  AuthenticatedProjectsProjectIdFlagsRouteImport.update({
    id: '/projects/$projectId/flags',
    path: '/projects/$projectId/flags',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdEnvironmentsRoute =
  AuthenticatedProjectsProjectIdEnvironmentsRouteImport.update({
    id: '/projects/$projectId/environments',
    path: '/projects/$projectId/environments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdFlagsFlagIdRoute =
  AuthenticatedProjectsProjectIdFlagsFlagIdRouteImport.update({
    id: '/$flagId',
    path: '/$flagId',
    getParentRoute: () => AuthenticatedProjectsProjectIdFlagsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectId/environments': typeof AuthenticatedProjectsProjectIdEnvironmentsRoute
  '/projects/$projectId/flags': typeof AuthenticatedProjectsProjectIdFlagsRouteWithChildren
  '/projects/$projectId/sdk-keys': typeof AuthenticatedProjectsProjectIdSdkKeysRoute
  '/projects/$projectId/flags/$flagId': typeof AuthenticatedProjectsProjectIdFlagsFlagIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectId/environments': typeof AuthenticatedProjectsProjectIdEnvironmentsRoute
  '/projects/$projectId/flags': typeof AuthenticatedProjectsProjectIdFlagsRouteWithChildren
  '/projects/$projectId/sdk-keys': typeof AuthenticatedProjectsProjectIdSdkKeysRoute
  '/projects/$projectId/flags/$flagId': typeof AuthenticatedProjectsProjectIdFlagsFlagIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/projects/$projectId/environments': typeof AuthenticatedProjectsProjectIdEnvironmentsRoute
  '/_authenticated/projects/$projectId/flags': typeof AuthenticatedProjectsProjectIdFlagsRouteWithChildren
  '/_authenticated/projects/$projectId/sdk-keys': typeof AuthenticatedProjectsProjectIdSdkKeysRoute
  '/_authenticated/projects/$projectId/flags/$flagId': typeof AuthenticatedProjectsProjectIdFlagsFlagIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/projects/'
    | '/projects/$projectId/environments'
    | '/projects/$projectId/flags'
    | '/projects/$projectId/sdk-keys'
    | '/projects/$projectId/flags/$flagId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/projects'
    | '/projects/$projectId/environments'
    | '/projects/$projectId/flags'
    | '/projects/$projectId/sdk-keys'
    | '/projects/$projectId/flags/$flagId'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_authenticated/'
    | '/_authenticated/projects/'
    | '/_authenticated/projects/$projectId/environments'
    | '/_authenticated/projects/$projectId/flags'
    | '/_authenticated/projects/$projectId/sdk-keys'
    | '/_authenticated/projects/$projectId/flags/$flagId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/sdk-keys': {
      id: '/_authenticated/projects/$projectId/sdk-keys'
      path: '/projects/$projectId/sdk-keys'
      fullPath: '/projects/$projectId/sdk-keys'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSdkKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/flags': {
      id: '/_authenticated/projects/$projectId/flags'
      path: '/projects/$projectId/flags'
      fullPath: '/projects/$projectId/flags'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdFlagsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/environments': {
      id: '/_authenticated/projects/$projectId/environments'
      path: '/projects/$projectId/environments'
      fullPath: '/projects/$projectId/environments'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEnvironmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/flags/$flagId': {
      id: '/_authenticated/projects/$projectId/flags/$flagId'
      path: '/$flagId'
      fullPath: '/projects/$projectId/flags/$flagId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdFlagsFlagIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdFlagsRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedProjectsProjectIdFlagsRouteChildren {
  AuthenticatedProjectsProjectIdFlagsFlagIdRoute: typeof AuthenticatedProjectsProjectIdFlagsFlagIdRoute
}

const AuthenticatedProjectsProjectIdFlagsRouteChildren: AuthenticatedProjectsProjectIdFlagsRouteChildren =
  {
    AuthenticatedProjectsProjectIdFlagsFlagIdRoute:
      AuthenticatedProjectsProjectIdFlagsFlagIdRoute,
  }

const AuthenticatedProjectsProjectIdFlagsRouteWithChildren =
  AuthenticatedProjectsProjectIdFlagsRoute._addFileChildren(
    AuthenticatedProjectsProjectIdFlagsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedProjectsProjectIdEnvironmentsRoute: typeof AuthenticatedProjectsProjectIdEnvironmentsRoute
  AuthenticatedProjectsProjectIdFlagsRoute: typeof AuthenticatedProjectsProjectIdFlagsRouteWithChildren
  AuthenticatedProjectsProjectIdSdkKeysRoute: typeof AuthenticatedProjectsProjectIdSdkKeysRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedProjectsProjectIdEnvironmentsRoute:
    AuthenticatedProjectsProjectIdEnvironmentsRoute,
  AuthenticatedProjectsProjectIdFlagsRoute:
    AuthenticatedProjectsProjectIdFlagsRouteWithChildren,
  AuthenticatedProjectsProjectIdSdkKeysRoute:
    AuthenticatedProjectsProjectIdSdkKeysRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
