/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated/audit-logs'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedProjectsProjectSlugRouteRouteImport } from './routes/_authenticated/projects/$projectSlug/route'
import { Route as AuthenticatedProjectsProjectSlugSdkKeysRouteImport } from './routes/_authenticated/projects/$projectSlug/sdk-keys'
import { Route as AuthenticatedProjectsProjectSlugFlagsRouteImport } from './routes/_authenticated/projects/$projectSlug/flags'
import { Route as AuthenticatedProjectsProjectSlugEnvironmentsRouteImport } from './routes/_authenticated/projects/$projectSlug/environments'
import { Route as AuthenticatedProjectsProjectSlugFlagsFlagIdRouteImport } from './routes/_authenticated/projects/$projectSlug/flags/$flagId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectSlugRouteRoute =
  AuthenticatedProjectsProjectSlugRouteRouteImport.update({
    id: '/projects/$projectSlug',
    path: '/projects/$projectSlug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectSlugSdkKeysRoute =
  AuthenticatedProjectsProjectSlugSdkKeysRouteImport.update({
    id: '/sdk-keys',
    path: '/sdk-keys',
    getParentRoute: () => AuthenticatedProjectsProjectSlugRouteRoute,
  } as any)
const AuthenticatedProjectsProjectSlugFlagsRoute =
  AuthenticatedProjectsProjectSlugFlagsRouteImport.update({
    id: '/flags',
    path: '/flags',
    getParentRoute: () => AuthenticatedProjectsProjectSlugRouteRoute,
  } as any)
const AuthenticatedProjectsProjectSlugEnvironmentsRoute =
  AuthenticatedProjectsProjectSlugEnvironmentsRouteImport.update({
    id: '/environments',
    path: '/environments',
    getParentRoute: () => AuthenticatedProjectsProjectSlugRouteRoute,
  } as any)
const AuthenticatedProjectsProjectSlugFlagsFlagIdRoute =
  AuthenticatedProjectsProjectSlugFlagsFlagIdRouteImport.update({
    id: '/$flagId',
    path: '/$flagId',
    getParentRoute: () => AuthenticatedProjectsProjectSlugFlagsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/projects/$projectSlug': typeof AuthenticatedProjectsProjectSlugRouteRouteWithChildren
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectSlug/environments': typeof AuthenticatedProjectsProjectSlugEnvironmentsRoute
  '/projects/$projectSlug/flags': typeof AuthenticatedProjectsProjectSlugFlagsRouteWithChildren
  '/projects/$projectSlug/sdk-keys': typeof AuthenticatedProjectsProjectSlugSdkKeysRoute
  '/projects/$projectSlug/flags/$flagId': typeof AuthenticatedProjectsProjectSlugFlagsFlagIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/projects/$projectSlug': typeof AuthenticatedProjectsProjectSlugRouteRouteWithChildren
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectSlug/environments': typeof AuthenticatedProjectsProjectSlugEnvironmentsRoute
  '/projects/$projectSlug/flags': typeof AuthenticatedProjectsProjectSlugFlagsRouteWithChildren
  '/projects/$projectSlug/sdk-keys': typeof AuthenticatedProjectsProjectSlugSdkKeysRoute
  '/projects/$projectSlug/flags/$flagId': typeof AuthenticatedProjectsProjectSlugFlagsFlagIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/projects/$projectSlug': typeof AuthenticatedProjectsProjectSlugRouteRouteWithChildren
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/projects/$projectSlug/environments': typeof AuthenticatedProjectsProjectSlugEnvironmentsRoute
  '/_authenticated/projects/$projectSlug/flags': typeof AuthenticatedProjectsProjectSlugFlagsRouteWithChildren
  '/_authenticated/projects/$projectSlug/sdk-keys': typeof AuthenticatedProjectsProjectSlugSdkKeysRoute
  '/_authenticated/projects/$projectSlug/flags/$flagId': typeof AuthenticatedProjectsProjectSlugFlagsFlagIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/audit-logs'
    | '/projects/$projectSlug'
    | '/projects/'
    | '/projects/$projectSlug/environments'
    | '/projects/$projectSlug/flags'
    | '/projects/$projectSlug/sdk-keys'
    | '/projects/$projectSlug/flags/$flagId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/audit-logs'
    | '/projects/$projectSlug'
    | '/projects'
    | '/projects/$projectSlug/environments'
    | '/projects/$projectSlug/flags'
    | '/projects/$projectSlug/sdk-keys'
    | '/projects/$projectSlug/flags/$flagId'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_authenticated/audit-logs'
    | '/_authenticated/'
    | '/_authenticated/projects/$projectSlug'
    | '/_authenticated/projects/'
    | '/_authenticated/projects/$projectSlug/environments'
    | '/_authenticated/projects/$projectSlug/flags'
    | '/_authenticated/projects/$projectSlug/sdk-keys'
    | '/_authenticated/projects/$projectSlug/flags/$flagId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectSlug': {
      id: '/_authenticated/projects/$projectSlug'
      path: '/projects/$projectSlug'
      fullPath: '/projects/$projectSlug'
      preLoaderRoute: typeof AuthenticatedProjectsProjectSlugRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectSlug/sdk-keys': {
      id: '/_authenticated/projects/$projectSlug/sdk-keys'
      path: '/sdk-keys'
      fullPath: '/projects/$projectSlug/sdk-keys'
      preLoaderRoute: typeof AuthenticatedProjectsProjectSlugSdkKeysRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectSlugRouteRoute
    }
    '/_authenticated/projects/$projectSlug/flags': {
      id: '/_authenticated/projects/$projectSlug/flags'
      path: '/flags'
      fullPath: '/projects/$projectSlug/flags'
      preLoaderRoute: typeof AuthenticatedProjectsProjectSlugFlagsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectSlugRouteRoute
    }
    '/_authenticated/projects/$projectSlug/environments': {
      id: '/_authenticated/projects/$projectSlug/environments'
      path: '/environments'
      fullPath: '/projects/$projectSlug/environments'
      preLoaderRoute: typeof AuthenticatedProjectsProjectSlugEnvironmentsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectSlugRouteRoute
    }
    '/_authenticated/projects/$projectSlug/flags/$flagId': {
      id: '/_authenticated/projects/$projectSlug/flags/$flagId'
      path: '/$flagId'
      fullPath: '/projects/$projectSlug/flags/$flagId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectSlugFlagsFlagIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectSlugFlagsRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedProjectsProjectSlugFlagsRouteChildren {
  AuthenticatedProjectsProjectSlugFlagsFlagIdRoute: typeof AuthenticatedProjectsProjectSlugFlagsFlagIdRoute
}

const AuthenticatedProjectsProjectSlugFlagsRouteChildren: AuthenticatedProjectsProjectSlugFlagsRouteChildren =
  {
    AuthenticatedProjectsProjectSlugFlagsFlagIdRoute:
      AuthenticatedProjectsProjectSlugFlagsFlagIdRoute,
  }

const AuthenticatedProjectsProjectSlugFlagsRouteWithChildren =
  AuthenticatedProjectsProjectSlugFlagsRoute._addFileChildren(
    AuthenticatedProjectsProjectSlugFlagsRouteChildren,
  )

interface AuthenticatedProjectsProjectSlugRouteRouteChildren {
  AuthenticatedProjectsProjectSlugEnvironmentsRoute: typeof AuthenticatedProjectsProjectSlugEnvironmentsRoute
  AuthenticatedProjectsProjectSlugFlagsRoute: typeof AuthenticatedProjectsProjectSlugFlagsRouteWithChildren
  AuthenticatedProjectsProjectSlugSdkKeysRoute: typeof AuthenticatedProjectsProjectSlugSdkKeysRoute
}

const AuthenticatedProjectsProjectSlugRouteRouteChildren: AuthenticatedProjectsProjectSlugRouteRouteChildren =
  {
    AuthenticatedProjectsProjectSlugEnvironmentsRoute:
      AuthenticatedProjectsProjectSlugEnvironmentsRoute,
    AuthenticatedProjectsProjectSlugFlagsRoute:
      AuthenticatedProjectsProjectSlugFlagsRouteWithChildren,
    AuthenticatedProjectsProjectSlugSdkKeysRoute:
      AuthenticatedProjectsProjectSlugSdkKeysRoute,
  }

const AuthenticatedProjectsProjectSlugRouteRouteWithChildren =
  AuthenticatedProjectsProjectSlugRouteRoute._addFileChildren(
    AuthenticatedProjectsProjectSlugRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProjectsProjectSlugRouteRoute: typeof AuthenticatedProjectsProjectSlugRouteRouteWithChildren
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProjectsProjectSlugRouteRoute:
    AuthenticatedProjectsProjectSlugRouteRouteWithChildren,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
